run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet: {} 

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - unused

issues:
  exclude-use-default: false
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
    - mock_.*\.go$
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
    - internal/repository/mocks
    - internal/service/mocks
  exclude:
    - G104
    - G112
    - exported func .* returns unexported type .*
    - should have a package comment
    - don't use an underscore in package name
    - Error return value of .*json.*Encoder.*Encode.* is not checked