// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	model "github.com/Dokhoyan/avito-pr-test/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// CreateTeamWithMembers provides a mock function with given fields: ctx, teamName, members
func (_m *MockTeamService) CreateTeamWithMembers(ctx context.Context, teamName string, members []model.TeamMember) (*model.Team, error) {
	ret := _m.Called(ctx, teamName, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamWithMembers")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.TeamMember) (*model.Team, error)); ok {
		return rf(ctx, teamName, members)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.TeamMember) *model.Team); ok {
		r0 = rf(ctx, teamName, members)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []model.TeamMember) error); ok {
		r1 = rf(ctx, teamName, members)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_CreateTeamWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamWithMembers'
type MockTeamService_CreateTeamWithMembers_Call struct {
	*mock.Call
}

// CreateTeamWithMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - members []model.TeamMember
func (_e *MockTeamService_Expecter) CreateTeamWithMembers(ctx interface{}, teamName interface{}, members interface{}) *MockTeamService_CreateTeamWithMembers_Call {
	return &MockTeamService_CreateTeamWithMembers_Call{Call: _e.mock.On("CreateTeamWithMembers", ctx, teamName, members)}
}

func (_c *MockTeamService_CreateTeamWithMembers_Call) Run(run func(ctx context.Context, teamName string, members []model.TeamMember)) *MockTeamService_CreateTeamWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]model.TeamMember))
	})
	return _c
}

func (_c *MockTeamService_CreateTeamWithMembers_Call) Return(_a0 *model.Team, _a1 error) *MockTeamService_CreateTeamWithMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_CreateTeamWithMembers_Call) RunAndReturn(run func(context.Context, string, []model.TeamMember) (*model.Team, error)) *MockTeamService_CreateTeamWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *MockTeamService) GetTeam(ctx context.Context, teamName string) (*model.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamService_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockTeamService_Expecter) GetTeam(ctx interface{}, teamName interface{}) *MockTeamService_GetTeam_Call {
	return &MockTeamService_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *MockTeamService_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockTeamService_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamService_GetTeam_Call) Return(_a0 *model.Team, _a1 error) *MockTeamService_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*model.Team, error)) *MockTeamService_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.Mock.AssertExpectations(t) })

	return mock
}
